import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by next.js",
};
export const NAV_ITEMS = [
  {
    label: "Product",
    href: "/product",
  },
  {
    label: "Docs",
    href: "/docs",
  },
  {
    label: "Login",
    href: "/login",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="flex items-center justify-between px-6 py-4 border-b">
          <div className="text-lg font-semibold">MyApp</div>

          <ul className="flex items-center gap-6">
            {NAV_ITEMS.map((item) => (
              <li key={item.href}>
                <Link
                  href={item.href}
                  className="text-sm text-gray-700 hover:text-black"
                >
                  {item.label}
                </Link>
              </li>
            ))}
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
